import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/data/context/AuthContext";
import { PrivateRoute } from "@/components/privateRoute/privateRoute";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Studio Raphael Oliveira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AuthProvider>
      <html lang="pt">
        <PrivateRoute>
          <body className={inter.className}>{children}</body>
        </PrivateRoute>
      </html>
    </AuthProvider>
  );
}
