import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/data/context/AuthContext";
import { generateThemeCss } from "@/lib/theme";
import theme from "@/config/theme.json";

export const metadata: Metadata = {
  title: "Studio Raphael Oliveira",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeCss = generateThemeCss(theme);

  return (
    <html lang="pt">
      <head>
        {/* Variáveis de tema geradas a partir de src/config/theme.json */}
        <style dangerouslySetInnerHTML={{ __html: themeCss }} />
      </head>
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
