import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Studio Raphael Oliveira",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}