'use client'

import { PrivateRoute } from "@/components/privateRoute/privateRoute";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Studio Raphael Oliveira",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrivateRoute>
      {children}
    </PrivateRoute>
  );
}
