name: Deploy Admin (production)

on:
  workflow_dispatch: {}         # roda manualmente
  push:
    tags:
      - 'v*'                    # ou por tag (v1.2.3)

concurrency:
  group: deploy-admin-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production     # usa secrets do Environment "production"

    steps:
      - name: Checkout (opcional)
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            APP_DIR="/var/www/prod/spingo-admin"
            PM2_NAME="spingo-admin-prod"
            PORT="3100"

            # Código: reseta sempre para a main remota
            cd "$APP_DIR"
            git fetch --all
            git reset --hard origin/main

            # .env de produção (decodifica do secret base64)
            echo "${{ secrets.ADMIN_ENV_B64 }}" | base64 -d > .env
            chmod 600 .env

            # Build e (re)start
            npm ci
            npm run build

            PORT="${PORT}" NODE_ENV=production \
            pm2 start "npm -- run start" --name "${PM2_NAME}" 2>/dev/null || true

            PORT="${PORT}" NODE_ENV=production \
            pm2 restart "${PM2_NAME}" --update-env

            pm2 save
