name: Deploy Admin (production)

on:
  push:
    branches:
      - main                  

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production     # usa secrets do Environment "production"

    steps:
      - name: Checkout (opcional)
        uses: actions/checkout@v4

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 212.85.2.8 >> ~/.ssh/known_hosts
          
      - name: Criar .env.local remoto
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@212.85.2.8 "cat <<EOF > /var/www/studio/studio-frontend/.env.local
            PORT=${{ secrets.PORT }}
            NEXT_PUBLIC_SERVER_URL_API=${{ secrets.NEXT_PUBLIC_SERVER_URL_API }}
            NEXT_PUBLIC_JWT_SECRET_KEY=${{ secrets.NEXT_PUBLIC_JWT_SECRET_KEY }}
          EOF"

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@212.85.2.8 << 'EOF'
            cd /var/www/prod/spingo-admin"
            GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa' git pull origin main
            npm install
            npm run build
            pm2 restart spingo-admin-prod || pm2 start npm --name spingo-admin-prod -- start
            pm2 save
          EOF
       
